### ISSUE TITLE
Issue with with Sphinx 3.0.0

### ISSUE THREAD

**Issue by agarny** [readthedocs/sphinx-hoverxref#65]
Hi, we have a project that makes use of sphinx-hoverxref and it builds fine using Sphinx 2.4.0, but not with Sphinx 3.0.0. Here is what we are getting when doing `make html` (here is the corresponding [log](https://github.com/readthedocs/sphinx-hoverxref/files/4490043/log.txt)):
```
sphinx-build -b html -d build/doctrees   src build/html
Running Sphinx v3.0.0
making output directory... done

Exception occurred:
  File "/Users/Alan/virtualenv/cellml-specification/lib/python3.7/site-packages/hoverxref/extension.py", line 198, in setup_sphinx_tabs
    for listener_id, function in app.events.listeners.get('html-page-context').items():
AttributeError: 'list' object has no attribute 'items'
The full traceback has been saved in /var/folders/k8/gmbwgb910z52mrztjsdwjpbh0000gn/T/sphinx-err-v2lr0bjq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

**Comment by humitos** [comment]
This is already fixed in master branch at https://github.com/humitos/sphinx-hoverxref/blob/humitos%2Fno-log-warnings/hoverxref/extension.py#L131-L137

I plan to do a new release today hopefully.

**Comment by agarny** [comment]
Great, thanks a lot.

**Comment by humitos** [comment]
@agarny I just pushed the release: `0.3b1`

I'm closing this issue, but feel free to reopen if you consider and let me know if it does work. Thanks!

**Comment by agarny** [comment]
Thanks a lot @humitos, I can confirm that it's all good now. Great!
